import * as argon2 from 'argon2';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const password = await argon2.hash('senha_forte_vistoriador');

  await prisma.user.createMany({
    data: [
      {
        name: 'Vistoriador Normal',
        email: 'vistoriador.normal@fake.io',
        password,
        role: 'vistoriador',
        status: true,
        cameraType: 'normal',
      },
      {
        name: 'Vistoriador 360',
        email: 'vistoriador.360@fake.io',
        password,
        role: 'vistoriador',
        status: true,
        cameraType: 'camera_360',
      },
    ],
    skipDuplicates: true,
  });

  await prisma.engineer.createMany({
    data: [
      {
        name: 'Cinara Aparecida Batista Gonçalves',
        email: 'cinara.goncalves@fagon.com.br',
        phone: '11980157566',
        cpf: '09118249876',
        education: 'Arquiteta',
        registrationEntity: 'CAU-SP',
        registrationNumber: 'A49590-5',
      },
      {
        name: 'Bárbara Cristina Gonçalves',
        email: 'barbara.goncalves@fagon.com.br',
        phone: '11979605000',
        cpf: '45594283833',
        education: 'Engenheira Civil',
        registrationEntity: 'CREA-SP',
        registrationNumber: '5070749165',
      },
      {
        name: 'Jennifer Ichiba da Silva',
        email: 'jennifer.ichiba@fagon.com.br',
        phone: '11942361837',
        cpf: '38873245870',
        education: 'Engenheira Civil',
        registrationEntity: 'CREA-SP',
        registrationNumber: '5070724848',
      },
    ],
    skipDuplicates: true,
  });

  await prisma.stateLaw.createMany({
    data: [
      {
        state: 'Acre',
        stateName: 'do Acre',
        primaryLawReference: 'NT Nº 08/2025',
        secondaryLawReference: 'NT Nº 10/2025',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMAC',
        primaryLawFullText: 'Norma Técnica (NT) Nº 08/2025',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 10/2025',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Alagoas',
        stateName: 'de Alagoas',
        primaryLawReference: 'IT Nº 08/2021',
        secondaryLawReference: 'IT Nº 10/2021',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMAL',
        primaryLawFullText: 'Instrução Técnica (IT) Nº 08/2021',
        secondaryLawFullText: 'Instrução Técnica (IT) Nº 10/2021',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Amapá',
        stateName: 'do Amapá',
        primaryLawReference: 'NT Nº 021/2020',
        secondaryLawReference: 'NT Nº 022/2020',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMAP',
        primaryLawFullText: 'Norma Técnica (NT) Nº 021/2020',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 022/2020',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Amazonas',
        stateName: 'do Amazonas',
        primaryLawReference: 'IT Nº 08/2025',
        secondaryLawReference: 'IT Nº 10/2025',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMAM',
        primaryLawFullText: 'Instrução Técnica (IT) Nº 08/2025',
        secondaryLawFullText: 'Instrução Técnica (IT) Nº 10/2025',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Bahia',
        stateName: 'da Bahia',
        primaryLawReference: 'IT Nº 08/2016',
        secondaryLawReference: 'IT Nº 10/2016',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMBA',
        primaryLawFullText: 'Instrução Técnica (IT) Nº 08/2016',
        secondaryLawFullText: 'Instrução Técnica (IT) Nº 10/2016',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Ceará',
        stateName: 'do Ceará',
        primaryLawReference: 'NT Nº 01/2024',
        secondaryLawReference: 'NT Nº 01/2024',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMCE',
        primaryLawFullText: 'Norma Técnica (NT) Nº 01/2024',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 01/2024',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Distrito Federal',
        stateName: 'do Distrito Federal',
        primaryLawReference: 'NT Nº 14/2022',
        secondaryLawReference: 'NT Nº 17/2022',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMDF',
        primaryLawFullText: 'Norma Técnica (NT) Nº 14/2022',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 17/2022',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Espírito Santo',
        stateName: 'do Espírito Santo',
        primaryLawReference: 'NT Nº 21/2022',
        secondaryLawReference: 'NT Nº 21/2022',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMES',
        primaryLawFullText: 'Norma Técnica (NT) Nº 21/2022',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 21/2022',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Goiás',
        stateName: 'de Goiás',
        primaryLawReference: 'NT Nº 08/2022',
        secondaryLawReference: 'NT Nº 10/2022',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMGO',
        primaryLawFullText: 'Norma Técnica (NT) Nº 08/2022',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 10/2022',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Maranhão',
        stateName: 'do Maranhão',
        primaryLawReference: 'NT Nº 08/2021',
        secondaryLawReference: 'NT Nº 10/2021',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMMA',
        primaryLawFullText: 'Norma Técnica (NT) Nº 08/2021',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 10/2021',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Mato Grosso',
        stateName: 'do Mato Grosso',
        primaryLawReference: 'NT Nº 12/2020',
        secondaryLawReference: 'NT Nº 12/2020',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMMT',
        primaryLawFullText: 'Norma Técnica (NT) Nº 12/2020',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 12/2020',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Mato Grosso do Sul',
        stateName: 'do Mato Grosso do Sul',
        primaryLawReference: 'NT Nº 08/2013',
        secondaryLawReference: 'NT Nº 10/2013',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMMS',
        primaryLawFullText: 'Norma Técnica (NT) Nº 08/2013',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 10/2013',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Minas Gerais',
        stateName: 'de Minas Gerais',
        primaryLawReference: 'IT Nº 06/2020',
        secondaryLawReference: 'IT Nº 38/2020',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMMG',
        primaryLawFullText: 'Instrução Técnica (IT) Nº 06/2020',
        secondaryLawFullText: 'Instrução Técnica (IT) Nº 38/2020',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Pará',
        stateName: 'do Pará',
        primaryLawReference: 'IT Nº 02/2019',
        secondaryLawReference: 'IT Nº 02/2019',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMPA',
        primaryLawFullText: 'Instrução Técnica (IT) Nº 02/2019',
        secondaryLawFullText: 'Instrução Técnica (IT) Nº 02/2019',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Paraíba',
        stateName: 'da Paraíba',
        primaryLawReference: 'NT Nº 08/2024',
        secondaryLawReference: 'NT Nº 10/2024',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMPB',
        primaryLawFullText: 'Norma Técnica (NT) Nº 08/2024',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 10/2024',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Paraná',
        stateName: 'do Paraná',
        primaryLawReference: 'NPT Nº 08/2011',
        secondaryLawReference: 'NPT Nº 10/2011',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMPR',
        primaryLawFullText: 'Norma de Procedimento Técnico (NPT) Nº 08/2011',
        secondaryLawFullText: 'Norma de Procedimento Técnico (NPT) Nº 10/2011',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Pernambuco',
        stateName: 'de Pernambuco',
        primaryLawReference: 'IT Nº 08/2025',
        secondaryLawReference: 'IT Nº 10/2025',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMPE',
        primaryLawFullText: 'Instrução Técnica (IT) Nº 08/2025',
        secondaryLawFullText: 'Instrução Técnica (IT) Nº 10/2025',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Piauí',
        stateName: 'do Piauí',
        primaryLawReference: 'NT Nº 08/2019',
        secondaryLawReference: 'NT Nº 10/2019',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMPI',
        primaryLawFullText: 'Norma Técnica (NT) Nº 08/2019',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 10/2019',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Rio de Janeiro',
        stateName: 'do Rio de Janeiro',
        primaryLawReference: 'NT Nº 02/2020',
        secondaryLawReference: 'NT Nº 02/2020',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMRJ',
        primaryLawFullText: 'Norma Técnica (NT) Nº 02/2020',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 02/2020',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Rio Grande do Norte',
        stateName: 'do Rio Grande do Norte',
        primaryLawReference: 'IT Nº 08/2022',
        secondaryLawReference: 'IT Nº 10/2022',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMRN',
        primaryLawFullText: 'Instrução Técnica (IT) Nº 08/2022',
        secondaryLawFullText: 'Instrução Técnica (IT) Nº 10/2022',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Rio Grande do Sul',
        stateName: 'do Rio Grande do Sul',
        primaryLawReference: 'IT Nº 08/2025',
        secondaryLawReference: 'IT Nº 10/2025',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMRS',
        primaryLawFullText: 'Instrução Técnica (IT) Nº 08/2025',
        secondaryLawFullText: 'Instrução Técnica (IT) Nº 10/2025',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Rondônia',
        stateName: 'de Rondônia',
        primaryLawReference: 'IT Nº 10/2017',
        secondaryLawReference: 'IT Nº 10/2017',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMRO',
        primaryLawFullText: 'Instrução Técnica (IT) Nº 10/2017',
        secondaryLawFullText: 'Instrução Técnica (IT) Nº 10/2017',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Roraima',
        stateName: 'de Roraima',
        primaryLawReference: 'NT Nº 10/2021',
        secondaryLawReference: 'NT Nº 10/2021',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMRR',
        primaryLawFullText: 'Norma Técnica (NT) Nº 10/2021',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 10/2021',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Santa Catarina',
        stateName: 'de Santa Catarina',
        primaryLawReference: 'IN Nº 18/2024',
        secondaryLawReference: 'IN Nº 18/2024',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMSC',
        primaryLawFullText: 'Instrução Normativa (IN) Nº 18/2024',
        secondaryLawFullText: 'Instrução Normativa (IN) Nº 18/2024',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'São Paulo',
        stateName: 'de São Paulo',
        primaryLawReference: 'IT Nº 08/2025',
        secondaryLawReference: 'IT Nº 10/2025',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMSP',
        primaryLawFullText: 'Instrução Técnica (IT) Nº 08/2025',
        secondaryLawFullText: 'Instrução Técnica (IT) Nº 10/2025',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Sergipe',
        stateName: 'de Sergipe',
        primaryLawReference: 'IT Nº 10/2021',
        secondaryLawReference: 'IT Nº 10/2021',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMSE',
        primaryLawFullText: 'Instrução Técnica (IT) Nº 10/2021',
        secondaryLawFullText: 'Instrução Técnica (IT) Nº 10/2021',
        complementaryLawFullText: '',
        active: true,
      },
      {
        state: 'Tocantins',
        stateName: 'do Tocantins',
        primaryLawReference: 'NT Nº 35/2022',
        secondaryLawReference: 'NT Nº 35/2022',
        complementaryLawReference: 'Lei Complementar Nº 14.376/2013',
        stateFireAbbreviation: 'CBMTO',
        primaryLawFullText: 'Norma Técnica (NT) Nº 35/2022',
        secondaryLawFullText: 'Norma Técnica (NT) Nº 35/2022',
        complementaryLawFullText: '',
        active: true,
      },
    ],
    skipDuplicates: true,
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => {
    void prisma.$disconnect();
  });
